const routes = {
  // auth screen"
  LOGIN_SCREEN: 'LOGIN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD',
  SIGNUP_SCREEN: 'SIGNUP',
  ACCOUNT_VERIFICATION_SCREEN: 'ACCOUNT_VERIFICATION',
  OTP_SCREEN: 'OTP_SCREEN',
  WELCOME_SCREEN: 'WELCOME',
  // public
  HOME_SCREEN: 'HOME',
  ABOUT_SCREEN: 'ABOUT',
  CATEGORIES_SCREEN: 'CATEGORY',
  WALLET_SCREEN: 'WALLET_SCREEN',
  OFFERS_SCREEN: 'OFFERS',
  PROFILE_SCREEN: 'SCREEN_SCREEN',
  SEARCH_SCREEN: 'SEARCH',
  // product
  PRODUCT_DETAILS: 'PRODUCT',
  // cart details
  CART_SCREEN: 'CART',
  REQ_LOGIN: 'REQ_LOGIN',
  USERS_ADDRESS: 'USER_ADDRESS',
  ADD_ADDRESS: 'ADD_ADDRESS',
  ORDER_SUMMARY: 'ORDER_SUMMARY',
  PAYMENT_SCREEN: 'PAYMENT_SCREEN',
  ORDER_SUCCESS: 'ORDER_SUCCESS',
  // private
  TRACK_ORDERS: 'TRACK_ORDERS',
  NOTIFICATION: 'NOTIFICATION',
  NOTIFICATIONS: 'NOTIFICATIONS',
  CONTACT_US: 'CONTACT_US',
  BRANCHES: 'BRANCHES',
  T_C: 'T_C',
};

export const routers = {
  AUTH_ROUTER: 'AUTH_ROUTER',
  NOTIFICATION_ROUTER: 'NOTIFICATION_ROUTE',
  CART_ROUTER: 'CART_ROUTER',
  PRODUCT_ROUTER: 'PRODUCT_ROUTE',
  PUBLIC_ROUTER: 'PUBLIC_ROUTER',
  TAB_ROUTER: 'TAB_ROUTER',
};

export default routes;
